### ISSUE TITLE
create user model

### ISSUE THREAD

**Issue by arkenwald** [mg-archie/green-thumbs#7]

**Comment by Mike5719** [comment]
const userSchema = new Schema({
  username: {
    type: String,
    required: true,
    unique: true,
    trim: true,
  },
  email: {
    type: String,
    required: true,
    unique: true,
    match: [/.+@.+\..+/, 'Must match an email address!'],
  },
  password: {
    type: String,
    required: true,
    minlength: 5,
  },
  blogs: [
    {
      type: Schema.Types.ObjectId,
      ref: 'Blog',
    },
  saved plants:

comments
  ],
});
